import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import About from "../components/About";
import Challenge from "../components/Challenge";
import Footer from "../components/Footer";
import HallOfFame from "../components/HallOfFame";
import Hero from "../components/Hero";
import Web3Modal from "web3modal";
import { Contract, providers, utils } from "ethers";
import Statistics from "../components/Statistics";

const Home: NextPage = () => {
    const [walletConnected, setWalletConnected] = useState(false);
    const [challenge, setChallenge] = useState("");
    const [days, setDays] = useState(0);
    const [trustedAccount, setTrustedAccount] = useState("");
    const [failedAccount, setFailedAccount] = useState("");

    const web3ModalRef = useRef();

    const getProviderOrSigner = async (needSigner = false) => {
        // Connect to Metamask
        // @ts-ignore: Object is possibly 'null'
        const provider = await web3ModalRef.current.connect();
        const web3Provider = new providers.Web3Provider(provider);

        // If user is not connected to the Rinkeby network, let them know and throw an error
        const { chainId } = await web3Provider.getNetwork();
        if (chainId !== 80001) {
            window.alert("Change the network to Mumbai");
            throw new Error("Change network to Mumbai");
        }

        if (needSigner) {
            const signer = web3Provider.getSigner();
            return signer;
        }
        return web3Provider;
    };

    const connectWallet = async () => {
        try {
            await getProviderOrSigner();
            setWalletConnected(true);
        } catch (error) {
            console.log(error);
        }
    };

    useEffect(() => {
        if (!walletConnected) {
            web3ModalRef.current = new Web3Modal({
                network: "mumbai",
                providerOptions: {},
                disableInjectedProvider: false,
            }) as any;
            connectWallet();
        }
    }, [walletConnected]);

    return (
        <div>
            <Head>
                <title>Decetable</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link
                    rel='apple-touch-icon'
                    sizes='180x180'
                    href='/favicon/apple-touch-icon.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='32x32'
                    href='/favicon/favicon-32x32.png'
                />
                <link
                    rel='icon'
                    type='image/png'
                    sizes='16x16'
                    href='/favicon/favicon-16x16.png'
                />
                <link rel='manifest' href='/favicon/site.webmanifest' />
                <link
                    rel='mask-icon'
                    href='/favicon/safari-pinned-tab.svg'
                    color='#5bbad5'
                />
                <meta name='msapplication-TileColor' content='#da532c' />
                <meta name='theme-color' content='#ffffff' />
            </Head>

            <main className='bg-main'>
                <Hero />
                <About />
                <Challenge
                    challenge={challenge}
                    days={days}
                    trustedAccount={trustedAccount}
                />
                <Statistics />
                <HallOfFame />
            </main>

            <Footer />
        </div>
    );
};

export default Home;
